---
- name: get os release
  command: lsb_release -cs
  register: lsb_release_result
  changed_when: false
  tags: [ postgresql ]
- name: add postgresql apt repository
  lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    regexp: "apt.postgresql.org"
    line: "deb http://apt.postgresql.org/pub/repos/apt/ {{ lsb_release_result.stdout.strip() }}-pgdg main"
    create: yes
  register: postgresql_apt_repository_result
  tags: [ postgresql ]
- name: add postgresql signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  register: postgresql_signing_key_result
  tags: [ postgresql ]
- name: update apt cache
  apt:
    update_cache: yes
  when: postgresql_apt_repository_result|changed or postgresql_signing_key_result|changed
  tags: [ postgresql ]
- name: install postgresql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - postgis
  tags: [ postgresql ]
- name: configure postgresql authentication
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - reload postgresql
  tags: [ postgresql ]
- name: start postgresql
  service:
    name: postgresql
    state: started
  tags: [ postgresql ]
