---
- name: create backend config file
  template:
    src: .env
    dest: /var/www/biosentiers/backend/.env
    owner: biosentiers
    group: biosentiers
    mode: 0640
- name: set backend node version
  template:
    src: .node-version
    dest: /var/www/biosentiers/backend/.node-version
    owner: biosentiers
    group: biosentiers
    mode: 0640
