---
- hosts: all
  become: true
  vars_files:
    - env.yml
  vars:
    server_name: biosentiers
  tasks:
    - name: build app docker image
      docker_image:
        name: 127.0.0.1:5000/biosentiers/app
        tag: deploy
        path: /vagrant/images/app
        force: true
        push: true
        buildargs:
          BIOSENTIERS_BACKEND_REF: deploy
          TIME: "{{ ansible_date_time.epoch }}"
        state: present
    - name: build db docker image
      docker_image:
        name: 127.0.0.1:5000/biosentiers/db
        path: /vagrant/images/db
        force: true
        push: true
        state: present
    - name: build rp docker image
      docker_image:
        name: 127.0.0.1:5000/biosentiers/rp
        path: /vagrant/images/rp
        force: true
        push: true
        state: present
    - name: clean up old images
      shell: docker images | grep '127.0.0.1:5000' | grep '<none>' | tr -s ' ' | sed 's/^ *//' | cut -d ' ' -f 3 | xargs docker rmi
      register: result
      changed_when: result.rc != 0
