---
- hosts: all
  become: true
  vars_files:
    - env.yml
  vars:
    server_name: biosentiers
  tasks:
    - name: build app docker image
      docker_image:
        name: biosentiers/app
        path: /srv/biosentiers/app
        force: true
        buildargs:
          BIOSENTIERS_BACKEND_REF: deploy
          TIME: "{{ ansible_date_time.epoch }}"
        state: present
    - name: build db docker image
      docker_image:
        name: biosentiers/db
        path: /srv/biosentiers/db
        force: true
        state: present
    - name: build rp docker image
      docker_image:
        name: biosentiers/rp
        path: /srv/biosentiers/rp
        force: true
        state: present
