---
- hosts: all
  become: true
  vars_files:
    - biosentiers.vagrant.yml
  vars:
    vagrant: true
    nginx_site_certbot_certificates_path: /var/ssl

  roles:

    # Generate a self-signed certificate
    - role: vagrant-ssl-cert
      vagrant_ssl_cert_name: biosentiers

    - role: base

    - role: firewall
      firewall_tcp_ports:
        - "22" # ssh
        - "80" # http
        - "443" # https

    # BioSentiers Node.js Backend & Angular Frontend
    - role: biosentiers

  tasks:

    - name: add local ssh key to root
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: add local ssh key to biosentiers
      authorized_key:
        user: biosentiers
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
