---
- hosts: all
  become: true
  vars_files:
    - env.yml
  vars:
    server_name: biosentiers
    docker_compose_version: 1.12.0
    docker_network_name: "{{ server_name }}"
  roles:
    - role: vagrant
    - role: biosentiers
  tasks:
    - name: add local ssh key to root
      authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
